
import { Mastra } from '@mastra/core';
import { AfricanCXFactory } from './core/engine/factory';
import { solimiConfig } from './tenants/solimi';

// ==========================================================
// AFRICAN-CX : SINGLE TENANT ENTRY POINT
// ==========================================================

// Charger la config du tenant (Solimi par défaut)
const currentTenant = solimiConfig;

// LA FACTORY : Générer les agents dynamiquement
const factoryResult = AfricanCXFactory.createTenant(currentTenant);

// Assembler les agents dans un objet plat pour Mastra
const agents: Record<string, any> = {
    [`${currentTenant.id}_support`]: factoryResult.mainAgent,
    ...factoryResult.specialistAgents
};

console.log("DEBUG: Agents generated by Factory:", Object.keys(agents)); // Debug ici
console.log("DEBUG: Agents generated by Factory:", Object.keys(agents));

export const mastra = new Mastra({
    agents: agents,
});

export default mastra;
